name: release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # checkout
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # setup go environment
      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache: true
      
      # release
      - uses: goreleaser/goreleaser-action@v4
        with:
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}